<?php
//halaman awal
 if(isset($_GET['masuk'])){ 
include'sign-in.php';
}
 if(isset($_GET['keluar'])){ 
include'sign-out.php';
} 
if(isset($_GET['process-masuk'])){ 
include'process-sign-in.php';
}
if(isset($_GET['lupa-sandi'])){ 
include'reset.php';
}

//halaman error session
 if(isset($_GET['acces-admin'])){ 
include'system/error/acces-admin.php';
}
 if(isset($_GET['acces-dosen'])){ 
include'system/error/acces-dosen.php';
}
if(isset($_GET['error-404'])){ 
include'system/error/404.php';
}

//halaman admin
 if(isset($_GET['home'])){ 
include'system/admin/home.php';
}
 if(isset($_GET['data-semua-mahasiswa'])){ 
include'system/admin/data-all-mahasiswa.php';
} 
if(isset($_GET['data-kelas'])){ 
include'system/admin/data-kelas.php';
}
if(isset($_GET['data-mahasiswa'])){ 
include'system/admin/data-mahasiswa.php';
}
if(isset($_GET['data-user'])){ 
include'system/admin/data-user.php';
}
if(isset($_GET['delete-kelas'])){ 
include'system/admin/delete-kelas.php';
}
if(isset($_GET['delete-mahasiswa'])){ 
include'system/admin/delete-mahasiswa.php';
}
if(isset($_GET['delete-user'])){ 
include'system/admin/delete-user.php';
}
if(isset($_GET['edit-kelas'])){ 
include'system/admin/edit-kelas.php';
}
if(isset($_GET['edit-mahasiswa'])){ 
include'system/admin/edit-mahasiswa.php';
}
if(isset($_GET['edit-user'])){ 
include'system/admin/edit-user.php';
}
if(isset($_GET['tambah-kelas'])){ 
include'system/admin/insert-kelas.php';
}
if(isset($_GET['tambah-mahasiswa'])){ 
include'system/admin/insert-mahasiswa.php';
}
if(isset($_GET['tambah-user'])){ 
include'system/admin/insert-user.php';
}
 if(isset($_GET['process-edit-kelas'])){ 
include'system/admin/process-edit-kelas.php';
} 
 if(isset($_GET['process-edit-mahasiswa'])){ 
include'system/admin/process-edit-mahasiswa.php';
} 
 if(isset($_GET['process-edit-user'])){ 
include'system/admin/process-edit-user.php';
}  
 if(isset($_GET['process-insert-kelas'])){ 
include'system/admin/process-insert-kelas.php';
} 
 if(isset($_GET['process-insert-mahasiswa'])){ 
include'system/admin/process-insert-mahasiswa.php';
} 
 if(isset($_GET['process-insert-user'])){ 
include'system/admin/process-insert-user.php';
} 
if(isset($_GET['detail-kelas'])){ 
include'system/admin/view-kelas.php';
}  
if(isset($_GET['detail-mahasiswa'])){ 
include'system/admin/view-mahasiswa.php';
}  
if(isset($_GET['detail-user'])){ 
include'system/admin/view-user.php';
}
if(isset($_GET['about'])){ 
include'system/admin/about.php';
}
if(isset($_GET['bantuan'])){ 
include'system/admin/help.php';
}

//halaman dosen
 if(isset($_GET['g-home'])){ 
include'system/dosen/home.php';
}
 if(isset($_GET['g-data-absensi'])){ 
include'system/dosen/data-absensi.php';
}
 if(isset($_GET['rekap-absensi'])){ 
include'system/dosen/rekap-absensi.php';
}
if(isset($_GET['g-data-kelas'])){ 
include'system/dosen/data-kelas.php';
}
if(isset($_GET['g-data-mahasiswa'])){ 
include'system/dosen/data-mahasiswa.php';
}
if(isset($_GET['g-edit-profil'])){ 
include'system/dosen/edit-profil.php';
}
 if(isset($_GET['g-process-edit-profil'])){ 
include'system/dosen/process-edit-profil.php';
}  
if(isset($_GET['g-detail-kelas'])){ 
include'system/dosen/view-kelas.php';
}  
if(isset($_GET['g-detail-mahasiswa'])){ 
include'system/dosen/view-mahasiswa.php';
}  
if(isset($_GET['g-detail-profil'])){ 
include'system/dosen/view-profil.php';
}
if(isset($_GET['g-about'])){ 
include'system/dosen/about.php';
}
if(isset($_GET['g-bantuan'])){ 
include'system/dosen/help.php';
}